### ISSUE TITLE
老师有遇到刷新丢失内容的问题么

### ISSUE THREAD

**Issue by reckless-huang** [chodocs/chodocs#323]
我在官方贴了issue，没人处理刷到您的站点发现是正常的 https://github.com/vuejs/vitepress/issues/4410

**Comment by shendiid** [comment]
> 我在官方贴了issue，没人处理刷到您的站点发现是正常的 [vuejs/vitepress#4410](https://github.com/vuejs/vitepress/issues/4410)

请问解决了吗，我也遇到了

**Comment by reckless-huang** [comment]
测试来源仓库-同样有问题
去社区寻找答案没有相关issue-无
对比请求-发现空白页面请求了lean.js
google-看到了尤大在2020自豪的引入了lean.js
如何修复这个问题-提issue，同类问题review
思考lean是如何工作的，分析[https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts，发现主要是通过lean来识别的](https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts%EF%BC%8C%E5%8F%91%E7%8E%B0%E4%B8%BB%E8%A6%81%E6%98%AF%E9%80%9A%E8%BF%87lean%E6%9D%A5%E8%AF%86%E5%88%AB%E7%9A%84)
我是运维所以直接nginx梭哈rewrite了

        
        location ~* \.lean\.js$ {
        rewrite ^(.*)\.lean\.js$ $1.js last;
        }
测试下问题解决，持续半年的问题解决啦！🍭🍭🍭🍭

> > 我在官方贴了issue，没人处理刷到您的站点发现是正常的 [vuejs/vitepress#4410](https://github.com/vuejs/vitepress/issues/4410)
> 
> 请问解决了吗，我也遇到了

**Comment by shendiid** [comment]
> 测试来源仓库-同样有问题 去社区寻找答案没有相关issue-无 对比请求-发现空白页面请求了lean.js google-看到了尤大在2020自豪的引入了lean.js 如何修复这个问题-提issue，同类问题review 思考lean是如何工作的，分析[https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts，发现主要是通过lean来识别的](https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts%EF%BC%8C%E5%8F%91%E7%8E%B0%E4%B8%BB%E8%A6%81%E6%98%AF%E9%80%9A%E8%BF%87lean%E6%9D%A5%E8%AF%86%E5%88%AB%E7%9A%84) 我是运维所以直接nginx梭哈rewrite了
> 
> ```
>     location ~* \.lean\.js$ {
>     rewrite ^(.*)\.lean\.js$ $1.js last;
>     }
> ```
> 
> 测试下问题解决，持续半年的问题解决啦！🍭🍭🍭🍭
> 
> > > 我在官方贴了issue，没人处理刷到您的站点发现是正常的 [vuejs/vitepress#4410](https://github.com/vuejs/vitepress/issues/4410)
> > 
> > 
> > 请问解决了吗，我也遇到了

谢谢大佬，问题已解决

**Comment by reckless-huang** [comment]
> > 测试来源仓库-同样有问题 去社区寻找答案没有相关issue-无 对比请求-发现空白页面请求了lean.js google-看到了尤大在2020自豪的引入了lean.js 如何修复这个问题-提issue，同类问题review 思考lean是如何工作的，分析[https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts，发现主要是通过lean来识别的](https://github.com/vuejs/vitepress/blob/main/src/node/plugin.ts%EF%BC%8C%E5%8F%91%E7%8E%B0%E4%B8%BB%E8%A6%81%E6%98%AF%E9%80%9A%E8%BF%87lean%E6%9D%A5%E8%AF%86%E5%88%AB%E7%9A%84) 我是运维所以直接nginx梭哈rewrite了
> > ```
> >     location ~* \.lean\.js$ {
> >     rewrite ^(.*)\.lean\.js$ $1.js last;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试下问题解决，持续半年的问题解决啦！🍭🍭🍭🍭
> > > > 我在官方贴了issue，没人处理刷到您的站点发现是正常的 [vuejs/vitepress#4410](https://github.com/vuejs/vitepress/issues/4410)
> > > 
> > > 
> > > 请问解决了吗，我也遇到了
> 
> 谢谢大佬，问题已解决

有新的解决办法么
